"""empty message

Revision ID: 36acdcb6f3fd
Revises: 
Create Date: 2025-05-11 18:56:20.952573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36acdcb6f3fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
